version: '3.3'
services:
  app:
    image: musilic/stadium-ticket-system:v2
    expose:
      - 8080
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USERNAME: "${MYSQL_USER}"









