version: "3"

services:
  mysqld:
    image: mysql:latest
    container_name: eticket-system
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: makutano
      MYSQL_DATABASE: eticket
    volumes:
      - mysql-data:/var/lib/mysql

  eticket-system:
    image: musilic/eticket-system:v1
    ports:
      - "8090:8090"
    depends_on:
      mysqld:
        condition: service_started
    environment:
      MYSQL_HOST: mysqld
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: makutano
      MYSQL_DATABASE: eticket

volumes:
  mysql-data: