- name: Deploy Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Create Target Directory
      file:
        path: musili/stadium
        state: directory
        recurse: yes
        owner: musili

    - name: Ensure Docker Compose is installed
      become: yes
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == 'Debian'

    - name: Copy Docker Compose File
      copy:
        src: ./docker-compose.yml
        dest: musili/stadium/docker-compose.yml

    - name: Run Docker Compose
      shell: |
        docker compose -f musili/stadium/docker-compose.yml pull
        docker compose -f musili/stadium/docker-compose.yml up -d